name: Pull Request

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  workflow_dispatch:
    branches: [ 'master' ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# Add "id-token" with the intended permissions.
permissions:
  contents: 'read'
  id-token: 'write'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install python
        if: success() # Last step was performed successfully
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        if: success() # Last step was performed successfully
        run: |
          pip install -r dev-requirements.txt
          pip install -r requirements.txt

      - name: Build
        if: success()
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine build
          python -m build

      - name: Pylint
        if: success()
        run: |
          python pylint $(find . -name '*.py')